config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'users#index'

  resources :users do
    resources :items, only: [:create, :show, :destroy]
  end

  resources :items, only: [:destroy]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user

  validates :user, presence: true
  validates :name, length: {minimum: 3}, presence: true

  default_scope { order('created_at DESC') }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
  has_many :items
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def create
    @item = current_user.items.new(item_params)

    if @item.save
      flash[:notice] = "Your item was successfully saved!"
    else
      flash.now[:alert] = "There was an error saving your item. Please try again."
    end
    redirect_to user_path(current_user)
  end

  def edit
    @item = current_user.items.find(params[:id])
  end

  def update
    @item = current_user.items.find(params[:id])
    @item.update_attribute(item_params)

    if @item.update
      flash[:notice] = "Item was updated successfully"
      redirect_to [@item]
    else
      flash[:alert] = "Item did not update"
      render :edit
    end
  end

  def destroy
    @item = current_user.items.find(params[:id])

    @item.destroy
    respond_to do |format|
      format.html { redirect_to user_path(:id), notice: 'Item was successfully removed!' }
      format.json { head :no_content }
    end
  end

  private

  def item_params
    params.require(:item).permit(:name)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def create
    @item = Item.new
  end

  def show
    @items = current_user.items
    # if you werent using devise use: @items = @user.items
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_form.html.erb
<%= form_for [current_user, item] do |f| %>
   <% if item.errors.any? %>
     <div class="alert alert-danger">
       <h4><%= pluralize(item.errors.count, "error") %>.</h4>
       <ul>
         <% item.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
       </ul>
     </div>
    <% end %>

    <div class="form-group">
      <h4><%= f.label :name, "Add a New To-Do!" %></h4>
      <%= f.text_field :name, class: 'form-control', placeholder: "Enter your item here!" %>
      <%= f.submit "Save", class: 'btn btn-success' %>
    </div>
<% end %>

app/views/items/_item.html.erb
<ul>
  <% @items.each do |i| %>
    <div class="col-md-6">
      <li><%= i.name %></li>
    </div>
    <div class="col-md-1">
      <%= link_to "", user_item_path(current_user, i), method: :delete, data: { confirm: 'Are you sure?', remote: true }, class: 'glyphicon glyphicon-ok' %>
    </div>
    <div class="col-md-2">
      <%= distance_of_time_in_words(Time.now, i.created_at + 7.days)%>
    </div>
  <% end %>
</ul>

app/views/items/destroy.js.erb
$('.delete').bind('ajax:success', function(){
    $(this).closest('li').fadeOut();
})

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blocitoff</title>
<!-- Roboto web font -->
 <link href="https://fonts.googleapis.com/css?family=Roboto:100,300,500,700" rel="stylesheet">
<!-- Bootstrap latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container">
      <% if flash[:notice] %>
      <div class="alert alert-success">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:notice] %>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-warning">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        <%= flash[:alert] %>
      </div>
    <% end %>

    <ul class="nav nav-tabs">
      <% if user_signed_in? %>
        <li><%= link_to current_user.email, user_path(:id) %></li>
      <% end %>


      <div class="pull-right user-info">
      <!-- user_signed_in?, current_user, user_session are all coming from devise -->
      <% if user_signed_in? %>
        <!--Signed in as: <strong><%= current_user.email %></strong> |-->

        <%= link_to 'Edit Profile', edit_user_registration_path, :class => 'navbar-link' %> | <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>

      <% else %>
        <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %> | <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
      <% end %>
    </div>
  </ul>

    <div class="f1">
      <%= yield %>
    </div>
  </body>
</html>

app/views/users/index.html.erb
<div class="jumbotron">
  <h1>Welcome to Blocitoff</h1>
  <div class="row">
    <div class="col-md-12">
      <h3>Let's make your week count!</h3>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<div class="To-Do">
  <h2>Your To-Do List</h2>
  <% if current_user %>
      <div class="col-md-3">
          <%= render 'items/form', item: Item.new %>
      </div>
      <div class="col-md-9">
        <div class='new-item'>
          <%= render 'items/item', locals: { item: @item } %>
        </div>
      </div>
  <% end %>
</div>